// <auto-generated />
using System;
using AppAlquiler_DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAlquiler_DataAccessLayer.Migrations
{
    [DbContext(typeof(AlquilerDbContext))]
    partial class AlquilerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.TypeMotorcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TypeMotorcycles");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("Fuel")
                        .HasColumnType("int");

                    b.Property<string>("GasolineConsumption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuggageCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelID")
                        .HasColumnType("int");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelID");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator().HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Bike", b =>
                {
                    b.HasBaseType("AppAlquiler_DataAccessLayer.Models.Vehicle");

                    b.Property<int>("FrameSize")
                        .HasColumnType("int");

                    b.Property<int>("NumberSpeeds")
                        .HasColumnType("int");

                    b.Property<int>("Whell")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Bike");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Boat", b =>
                {
                    b.HasBaseType("AppAlquiler_DataAccessLayer.Models.Vehicle");

                    b.Property<string>("Accessories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propulsion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("Sound")
                                .HasColumnName("Boat_Sound");
                        });

                    b.HasDiscriminator().HasValue("Boat");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Car", b =>
                {
                    b.HasBaseType("AppAlquiler_DataAccessLayer.Models.Vehicle");

                    b.Property<bool>("Abs")
                        .HasColumnType("bit");

                    b.Property<bool>("AirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("Airbag")
                        .HasColumnType("bit");

                    b.Property<float>("EngineLiters")
                        .HasColumnType("real");

                    b.Property<int>("NumberDoors")
                        .HasColumnType("int");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Vehicles", t =>
                        {
                            t.Property("Abs")
                                .HasColumnName("Car_Abs");
                        });

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Motorcycle", b =>
                {
                    b.HasBaseType("AppAlquiler_DataAccessLayer.Models.Vehicle");

                    b.Property<bool>("Abs")
                        .HasColumnType("bit");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeMotorcycleId")
                        .HasColumnType("int");

                    b.Property<int>("cilindrada")
                        .HasColumnType("int");

                    b.HasIndex("TypeMotorcycleId");

                    b.HasDiscriminator().HasValue("Motorcycle");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Vehicle", b =>
                {
                    b.HasOne("AppAlquiler_DataAccessLayer.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppAlquiler_DataAccessLayer.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AppAlquiler_DataAccessLayer.Models.Motorcycle", b =>
                {
                    b.HasOne("AppAlquiler_DataAccessLayer.Models.TypeMotorcycle", "TypeMotorcycle")
                        .WithMany()
                        .HasForeignKey("TypeMotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeMotorcycle");
                });
#pragma warning restore 612, 618
        }
    }
}
